import {
  STATUS,
  type ExecuteDetailData
} from '@/types/flow'

/**
 * 重试流水线响应数据
 */
export interface RetryPipelineResponse {
  id: string // 构建ID
  executeCount: number // 执行次数
  projectId: string // 项目ID
  pipelineId: string // 流水线ID
  num: number // 构建编号
  code?: number // 错误码（可选）
  message?: string // 错误信息（可选）
}

/**
 * 重放创作流状态
 */
export type ReplayStatus =
  | 'CANNOT_REPLAY'
  | 'CAN_REPLAY'
  | 'REPLAY_SUCCESS'
  | 'REPLAYING'
  | 'REPLAY_FAILED'

/**
 * 重放创作流响应数据
 */
export interface ReplayPipelineResponse {
  status: ReplayStatus // 重放状态
  id: string // 构建ID
  code?: number // 错误码（可选）
  message?: string // 错误信息（可选）
}

/**
 * 构建启动参数项
 */
export interface BuildParamItem {
  key: string
  value?: any
  valueType?: string
  readOnly?: boolean
  desc?: string
  defaultValue?: any
}

/**
 * 获取当前参数组合
 */
export interface BuildParamProperty {
  id: string
  name?: string
  required?: boolean
  constant?: boolean
  type?: string
  defaultValue?: any
  value?: any
  desc?: string
  readOnly?: boolean
  valueNotEmpty?: boolean
  removeFlag?: boolean
}

/**
 * 获取执行历史详情数据
 * @param projectId 项目ID
 * @param buildNo 构建编号
 * @param flowId 流水线ID
 * @param executeCount 执行次数（可选）
 * @returns 执行详情数据
 */
export function requestPipelineExecDetail({
  projectId,
  buildNo,
  flowId,
  executeCount,
}: {
  projectId: string
  buildNo: string
  flowId: string
  executeCount?: number
}): Promise<ExecuteDetailData> {
  // TODO: 调用实际接口
  // const url = executeCount
  //   ? `/user/builds/projects/${projectId}/pipelines/${flowId}/builds/${buildNo}/record?executeCount=${executeCount}`
  //   : `/user/builds/projects/${projectId}/pipelines/${flowId}/builds/${buildNo}/record`
  // return http.get(url)

  // Mock 数据 - 扩展版本，包含更复杂的编排流程
  return new Promise((resolve) => {
    setTimeout(() => {
      const baseTime = Date.now() - 3600000 // 1小时前
      resolve({
        id: 'b-d8311316d4a04e349f48102f9553b568',
        pipelineId: 'p-fc1ba8afdea34eed8a95e668879f4115',
        pipelineName: '复杂编排流程示例',
        userId: 'zhangsan',
        triggerUser: 'zhangsan',
        trigger: '手动',
        queueTime: baseTime,
        startTime: baseTime + 1485,
        queueTimeCost: 1485,
        endTime: baseTime + 224890,
        status: STATUS.SUCCEED,
        model: {
          '@type': 'Model',
          name: '复杂编排流程示例',
          desc: '这是一个包含多个阶段、矩阵容器和并行任务的复杂编排流程示例',
          stages: [
            // Stage 1: 构建触发
            {
              containers: [
                {
                  '@type': 'trigger',
                  id: '0',
                  name: '构建触发',
                  elements: [
                    {
                      '@type': 'manualTrigger',
                      name: '手动触发',
                      id: 'T-1-1-1',
                      status: STATUS.SUCCEED,
                      canElementSkip: false,
                      useLatestParameters: false,
                      executeCount: 3,
                      version: '1.*',
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: true,
                        timeout: 100,
                        timeoutVar: '100',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      asyncStatus: '',
                      classType: 'manualTrigger',
                      atomCode: 'manualTrigger',
                      taskAtom: '',
                    },
                    {
                      '@type': 'codeGitWebHookTrigger',
                      name: 'Git事件触发',
                      id: 'e-eafe4fd194dc4bf5b485a3e9c577c24b',
                      status: STATUS.SKIP,
                      pathFilterType: 'NamePrefixFilter',
                      eventType: 'PUSH',
                      repositoryType: 'NAME',
                      repositoryName: 'bkdevops-devx-dev/qqq4',
                      webhookQueue: false,
                      enableCheck: true,
                      includePushAction: ['push-file', 'new-branch'],
                      enableThirdFilter: false,
                      skipWip: false,
                      executeCount: 3,
                      version: '2.*',
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: true,
                        timeout: 100,
                        timeoutVar: '100',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      asyncStatus: '',
                      classType: 'codeGitWebHookTrigger',
                      atomCode: 'codeGitWebHookTrigger',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 1485,
                  systemElapsed: 1801,
                  elementElapsed: 0,
                  params: [],
                  canRetry: false,
                  containerId: '0',
                  containerHashId: 'c-a7a19916c56044d592280fbb31e081c5',
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 0,
                    executeCost: 0,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 0,
                  },
                  classType: 'trigger',
                },
              ],
              id: 'stage-1',
              name: '构建触发',
              status: STATUS.SUCCEED,
              elapsed: 507,
              fastKill: false,
              finally: false,
              canRetry: false,
              executeCount: 1,
              timeCost: {
                systemCost: 0,
                executeCost: 0,
                waitCost: 887,
                queueCost: 887,
                totalCost: 887,
              },
            },
            // Stage 2: 代码检查与构建
            {
              containers: [
                {
                  '@type': 'vmBuild',
                  id: '1',
                  name: '代码检查环境',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '代码规范检查',
                      id: 'e-lint-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run lint',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 900,
                        timeoutVar: '900',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 1250,
                      startEpoch: baseTime + 5000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 1250,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 1250,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                    {
                      '@type': 'linuxScript',
                      name: '单元测试',
                      id: 'e-test-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm test',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: true,
                        retryCount: 2,
                        manualRetry: false,
                        timeout: 1800,
                        timeoutVar: '1800',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 1,
                      retryCountManual: 0,
                      elapsed: 3200,
                      startEpoch: baseTime + 6500,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 3200,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 3200,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 5000,
                  systemElapsed: 14324,
                  elementElapsed: 4450,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '1',
                  containerHashId: 'c-2ab434d7271d48caa652e7e428212ba3',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 900,
                    timeoutVar: '900',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_FRn',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 14324,
                    executeCost: 4450,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 18774,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
                {
                  '@type': 'vmBuild',
                  id: '2',
                  name: '构建环境-Windows',
                  elements: [
                    {
                      '@type': 'windowsScript',
                      name: 'Windows构建',
                      id: 'e-win-build-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'BAT',
                      script: 'build.bat',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 1200,
                        timeoutVar: '1200',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 2800,
                      startEpoch: baseTime + 5000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 2800,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 2800,
                      },
                      asyncStatus: '',
                      classType: 'windowsScript',
                      atomCode: 'windowsScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 5000,
                  systemElapsed: 15200,
                  elementElapsed: 2800,
                  baseOS: 'WINDOWS',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'windows_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'windows_ci',
                    imageVersion: '2.1.0',
                    imageName: 'windows_ci',
                    dockerBuildVersion: 'windows_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '2',
                  containerHashId: 'c-win-build-001',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 1200,
                    timeoutVar: '1200',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Win',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 15200,
                    executeCost: 2800,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 18000,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
              ],
              id: 'stage-2',
              name: '代码检查与构建',
              tag: ['28ee946a59f64949a74f3dee40a1bda4'],
              status: STATUS.SUCCEED,
              startEpoch: baseTime + 5000,
              elapsed: 18774,
              fastKill: false,
              finally: false,
              canRetry: false,
              stageControlOption: {
                enable: true,
                runCondition: 'AFTER_LAST_FINISHED',
                customVariables: [],
                manualTrigger: false,
              },
              executeCount: 3,
              timeCost: {
                systemCost: 29524,
                executeCost: 7250,
                waitCost: 245,
                queueCost: 245,
                totalCost: 37019,
              },
            },
            // Stage 3: 矩阵构建（多环境并行）
            {
              containers: [
                {
                  '@type': 'vmBuild',
                  id: '3',
                  name: '多环境构建矩阵',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '构建应用',
                      id: 'e-matrix-build-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run build:$ENV',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 1800,
                        timeoutVar: '1800',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 4500,
                      startEpoch: baseTime + 45000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 4500,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 4500,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 45000,
                  systemElapsed: 12000,
                  elementElapsed: 4500,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '3',
                  containerHashId: 'c-matrix-build-001',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 1800,
                    timeoutVar: '1800',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Matrix',
                  containPostTaskFlag: false,
                  matrixGroupFlag: true,
                  groupContainers: [
                    {
                      '@type': 'vmBuild',
                      id: '3001',
                      name: '开发环境',
                      elements: [
                        {
                          '@type': 'linuxScript',
                          name: '构建应用',
                          id: 'e-matrix-dev-001',
                          status: STATUS.SUCCEED,
                          scriptType: 'SHELL',
                          script: 'npm run build:dev',
                          elapsed: 4200,
                          startEpoch: baseTime + 45000,
                          timeCost: {
                            systemCost: 0,
                            executeCost: 4200,
                            waitCost: 0,
                            queueCost: 0,
                            totalCost: 4200,
                          },
                          classType: 'linuxScript',
                          atomCode: 'linuxScript',
                        },
                      ],
                      status: STATUS.SUCCEED,
                      startEpoch: baseTime + 45000,
                      systemElapsed: 11000,
                      elementElapsed: 4200,
                      containerId: '3001',
                      containerHashId: 'c-matrix-dev-001',
                      matrixGroupFlag: false,
                      timeCost: {
                        systemCost: 11000,
                        executeCost: 4200,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 15200,
                      },
                      classType: 'vmBuild',
                    },
                    {
                      '@type': 'vmBuild',
                      id: '3002',
                      name: '测试环境',
                      elements: [
                        {
                          '@type': 'linuxScript',
                          name: '构建应用',
                          id: 'e-matrix-test-001',
                          status: STATUS.SUCCEED,
                          scriptType: 'SHELL',
                          script: 'npm run build:test',
                          elapsed: 4800,
                          startEpoch: baseTime + 45000,
                          timeCost: {
                            systemCost: 0,
                            executeCost: 4800,
                            waitCost: 0,
                            queueCost: 0,
                            totalCost: 4800,
                          },
                          classType: 'linuxScript',
                          atomCode: 'linuxScript',
                        },
                      ],
                      status: STATUS.SUCCEED,
                      startEpoch: baseTime + 45000,
                      systemElapsed: 12500,
                      elementElapsed: 4800,
                      containerId: '3002',
                      containerHashId: 'c-matrix-test-001',
                      matrixGroupFlag: false,
                      timeCost: {
                        systemCost: 12500,
                        executeCost: 4800,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 17300,
                      },
                      classType: 'vmBuild',
                    },
                    {
                      '@type': 'vmBuild',
                      id: '3003',
                      name: '生产环境',
                      elements: [
                        {
                          '@type': 'linuxScript',
                          name: '构建应用',
                          id: 'e-matrix-prod-001',
                          status: STATUS.SUCCEED,
                          scriptType: 'SHELL',
                          script: 'npm run build:prod',
                          elapsed: 5200,
                          startEpoch: baseTime + 45000,
                          timeCost: {
                            systemCost: 0,
                            executeCost: 5200,
                            waitCost: 0,
                            queueCost: 0,
                            totalCost: 5200,
                          },
                          classType: 'linuxScript',
                          atomCode: 'linuxScript',
                        },
                      ],
                      status: STATUS.SUCCEED,
                      startEpoch: baseTime + 45000,
                      systemElapsed: 13000,
                      elementElapsed: 5200,
                      containerId: '3003',
                      containerHashId: 'c-matrix-prod-001',
                      matrixGroupFlag: false,
                      timeCost: {
                        systemCost: 13000,
                        executeCost: 5200,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 18200,
                      },
                      classType: 'vmBuild',
                    },
                  ],
                  timeCost: {
                    systemCost: 36500,
                    executeCost: 14200,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 50700,
                  },
                  classType: 'vmBuild',
                },
              ],
              id: 'stage-3',
              name: '多环境构建',
              status: STATUS.SUCCEED,
              startEpoch: baseTime + 45000,
              elapsed: 50700,
              fastKill: false,
              finally: false,
              canRetry: false,
              executeCount: 3,
              timeCost: {
                systemCost: 36500,
                executeCost: 14200,
                waitCost: 0,
                queueCost: 0,
                totalCost: 50700,
              },
            },
            // Stage 4: 质量检查（包含多个Container，用于测试垂直滚动）
            {
              containers: [
                {
                  '@type': 'vmBuild',
                  id: '4',
                  name: '质量检查环境-1',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '代码覆盖率检查',
                      id: 'e-quality-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run coverage',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 1200,
                        timeoutVar: '1200',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 2800,
                      startEpoch: baseTime + 100000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 2800,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 2800,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                    {
                      '@type': 'linuxScript',
                      name: '安全扫描',
                      id: 'e-security-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm audit',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 900,
                        timeoutVar: '900',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 1500,
                      startEpoch: baseTime + 103000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 1500,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 1500,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                    {
                      '@type': 'linuxScript',
                      name: '性能测试',
                      id: 'e-performance-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run perf-test',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: true,
                        retryCount: 1,
                        manualRetry: false,
                        timeout: 2400,
                        timeoutVar: '2400',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 5600,
                      startEpoch: baseTime + 105000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 5600,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 5600,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 100000,
                  systemElapsed: 15000,
                  elementElapsed: 9900,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '4',
                  containerHashId: 'c-quality-001',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 2400,
                    timeoutVar: '2400',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Quality',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 15000,
                    executeCost: 9900,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 24900,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
                {
                  '@type': 'vmBuild',
                  id: '4-2',
                  name: '质量检查环境-2',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '代码质量分析',
                      id: 'e-quality-002',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run quality-check',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 1500,
                        timeoutVar: '1500',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 2100,
                      startEpoch: baseTime + 100000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 2100,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 2100,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 100000,
                  systemElapsed: 11000,
                  elementElapsed: 2100,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '4-2',
                  containerHashId: 'c-quality-002',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 1500,
                    timeoutVar: '1500',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Quality2',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 11000,
                    executeCost: 2100,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 13100,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
                {
                  '@type': 'vmBuild',
                  id: '4-3',
                  name: '质量检查环境-3',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '依赖检查',
                      id: 'e-quality-003',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm audit --audit-level=moderate',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 1000,
                        timeoutVar: '1000',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 1800,
                      startEpoch: baseTime + 100000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 1800,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 1800,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 100000,
                  systemElapsed: 10000,
                  elementElapsed: 1800,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '4-3',
                  containerHashId: 'c-quality-003',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 1000,
                    timeoutVar: '1000',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Quality3',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 10000,
                    executeCost: 1800,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 11800,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
                {
                  '@type': 'vmBuild',
                  id: '4-4',
                  name: '质量检查环境-4',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '代码复杂度检查',
                      id: 'e-quality-004',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'npm run complexity-check',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 2000,
                        timeoutVar: '2000',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 3500,
                      startEpoch: baseTime + 100000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 3500,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 3500,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 100000,
                  systemElapsed: 13000,
                  elementElapsed: 3500,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '4-4',
                  containerHashId: 'c-quality-004',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 2000,
                    timeoutVar: '2000',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Quality4',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 13000,
                    executeCost: 3500,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 16500,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
              ],
              id: 'stage-4',
              name: '质量检查',
              status: STATUS.SUCCEED,
              startEpoch: baseTime + 100000,
              elapsed: 24900,
              fastKill: false,
              finally: false,
              canRetry: false,
              executeCount: 3,
              timeCost: {
                systemCost: 49000,
                executeCost: 17300,
                waitCost: 0,
                queueCost: 0,
                totalCost: 66300,
              },
            },
            // Stage 5: 部署阶段
            {
              containers: [
                {
                  '@type': 'vmBuild',
                  id: '5',
                  name: '部署环境',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '部署到测试环境',
                      id: 'e-deploy-test-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'kubectl apply -f k8s/test.yaml',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: true,
                        retryCount: 2,
                        manualRetry: false,
                        timeout: 1800,
                        timeoutVar: '1800',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 3200,
                      startEpoch: baseTime + 130000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 3200,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 3200,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                    {
                      '@type': 'linuxScript',
                      name: '健康检查',
                      id: 'e-health-check-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'curl -f http://test.example.com/health',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: false,
                        manualSkip: false,
                        retryWhenFailed: true,
                        retryCount: 3,
                        manualRetry: false,
                        timeout: 600,
                        timeoutVar: '600',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 1,
                      retryCountManual: 0,
                      elapsed: 800,
                      startEpoch: baseTime + 133500,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 800,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 800,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 130000,
                  systemElapsed: 12000,
                  elementElapsed: 4000,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '5',
                  containerHashId: 'c-deploy-001',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 1800,
                    timeoutVar: '1800',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: false,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Deploy',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 12000,
                    executeCost: 4000,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 16000,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
              ],
              id: 'stage-5',
              name: '部署',
              status: STATUS.SUCCEED,
              startEpoch: baseTime + 130000,
              elapsed: 16000,
              fastKill: false,
              finally: false,
              canRetry: false,
              executeCount: 3,
              timeCost: {
                systemCost: 12000,
                executeCost: 4000,
                waitCost: 0,
                queueCost: 0,
                totalCost: 16000,
              },
            },
            // Finally Stage: 清理和通知
            {
              containers: [
                {
                  '@type': 'vmBuild',
                  id: '6',
                  name: '清理环境',
                  elements: [
                    {
                      '@type': 'linuxScript',
                      name: '清理临时文件',
                      id: 'e-cleanup-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'rm -rf /tmp/build-*',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: true,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 300,
                        timeoutVar: '300',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 500,
                      startEpoch: baseTime + 150000,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 500,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 500,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                    {
                      '@type': 'linuxScript',
                      name: '发送通知',
                      id: 'e-notify-001',
                      status: STATUS.SUCCEED,
                      scriptType: 'SHELL',
                      script: 'send-notification.sh',
                      continueNoneZero: false,
                      enableArchiveFile: false,
                      additionalOptions: {
                        enable: true,
                        continueWhenFailed: true,
                        manualSkip: false,
                        retryWhenFailed: false,
                        retryCount: 0,
                        manualRetry: false,
                        timeout: 300,
                        timeoutVar: '300',
                        runCondition: 'PRE_TASK_SUCCESS',
                        pauseBeforeExec: false,
                        subscriptionPauseUser: '',
                        customCondition: '',
                        enableCustomEnv: true,
                      },
                      executeCount: 3,
                      retryCount: 0,
                      retryCountManual: 0,
                      elapsed: 300,
                      startEpoch: baseTime + 150500,
                      version: '1.*',
                      timeCost: {
                        systemCost: 0,
                        executeCost: 300,
                        waitCost: 0,
                        queueCost: 0,
                        totalCost: 300,
                      },
                      asyncStatus: '',
                      classType: 'linuxScript',
                      atomCode: 'linuxScript',
                      taskAtom: '',
                    },
                  ],
                  status: STATUS.SUCCEED,
                  startEpoch: baseTime + 150000,
                  systemElapsed: 8000,
                  elementElapsed: 800,
                  baseOS: 'LINUX',
                  vmNames: [],
                  maxQueueMinutes: 60,
                  maxRunningMinutes: 900,
                  dispatchType: {
                    buildType: 'PUBLIC_DEVCLOUD',
                    value: 'tlinux_ci',
                    performanceConfigId: '0',
                    performanceUid: '',
                    persistence: false,
                    imageType: 'BKSTORE',
                    credentialId: '',
                    credentialProject: '',
                    imageCode: 'tlinux_ci',
                    imageVersion: '3.1.1',
                    imageName: 'tlinux_ci',
                    dockerBuildVersion: 'tlinux_ci',
                    imagePublicFlag: false,
                    imageRDType: '',
                    recommendFlag: true,
                  },
                  showBuildResource: false,
                  canRetry: false,
                  enableExternal: false,
                  containerId: '6',
                  containerHashId: 'c-cleanup-001',
                  jobControlOption: {
                    enable: true,
                    prepareTimeout: 10,
                    timeout: 300,
                    timeoutVar: '300',
                    runCondition: 'STAGE_RUNNING',
                    customVariables: [],
                    dependOnType: 'NAME',
                    continueWhenFailed: true,
                  },
                  startVMStatus: 'SUCCEED',
                  executeCount: 3,
                  jobId: 'job_Cleanup',
                  containPostTaskFlag: false,
                  matrixGroupFlag: false,
                  timeCost: {
                    systemCost: 8000,
                    executeCost: 800,
                    waitCost: 0,
                    queueCost: 0,
                    totalCost: 8800,
                  },
                  startVMTaskSeq: 1,
                  nfsSwitch: false,
                  classType: 'vmBuild',
                },
              ],
              id: 'stage-6',
              name: '清理和通知',
              status: STATUS.SUCCEED,
              startEpoch: baseTime + 150000,
              elapsed: 8800,
              fastKill: false,
              finally: true,
              canRetry: false,
              executeCount: 3,
              timeCost: {
                systemCost: 8000,
                executeCost: 800,
                waitCost: 0,
                queueCost: 0,
                totalCost: 8800,
              },
            },
          ],
          labels: ['production', 'ci/cd'],
          instanceFromTemplate: false,
          pipelineCreator: 'zhangsan',
          events: {},
          staticViews: [],
          timeCost: {
            systemCost: 155524,
            executeCost: 66750,
            waitCost: 1132,
            queueCost: 1485,
            totalCost: 224891,
          },
          latestVersion: 0,
        },
        currentTimestamp: Date.now(),
        buildNum: 3,
        curVersion: 4,
        curVersionName: 'V2(P2.T2.2)',
        latestVersion: 4,
        latestBuildNum: 3,
        lastModifyUser: 'zhangsan',
        executeTime: 66750,
        stageStatus: [
          {
            stageId: 'stage-1',
            name: '构建触发',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 1485,
            elapsed: 507,
          },
          {
            stageId: 'stage-2',
            name: '代码检查与构建',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 5000,
            elapsed: 18774,
          },
          {
            stageId: 'stage-3',
            name: '多环境构建',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 45000,
            elapsed: 50700,
          },
          {
            stageId: 'stage-4',
            name: '质量检查',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 100000,
            elapsed: 24900,
          },
          {
            stageId: 'stage-5',
            name: '部署',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 130000,
            elapsed: 16000,
          },
          {
            stageId: 'stage-6',
            name: '清理和通知',
            status: STATUS.SUCCEED,
            startEpoch: baseTime + 150000,
            elapsed: 8800,
          },
        ],
        executeCount: 3,
        startUserList: ['zhangsan', 'lisi', 'wangwu'],
        recordList: [
          {
            startUser: 'zhangsan',
            timeCost: {
              systemCost: 155524,
              executeCost: 66750,
              waitCost: 1132,
              queueCost: 1485,
              totalCost: 224891,
            },
          },
          {
            startUser: 'lisi',
            timeCost: {
              systemCost: 148000,
              executeCost: 65000,
              waitCost: 1050,
              queueCost: 1400,
              totalCost: 215450,
            },
          },
          {
            startUser: 'wangwu',
            timeCost: {
              systemCost: 142000,
              executeCost: 63000,
              waitCost: 980,
              queueCost: 1200,
              totalCost: 207180,
            },
          },
        ],
        buildMsg: '手动触发 - 复杂编排流程测试',
        debug: false,
        versionChange: false,
        cancelBuildPerm: true,
        remark: '这是一个包含多个阶段、矩阵容器和并行任务的复杂编排流程示例',
        material: [
          {
            scmType: 'CODE_GIT',
            aliasName: 'bkdevops/ci-flow',
            url: 'http://git.woa.com/bkdevops/ci-flow.git',
            branchName: 'master',
            newCommitId: '21fe7ff0cf16b2cd44b5b8a6d0e52a1c27c7dc94',
            commitTimes: 1,
            mainRepo: true,
            createTime: 1755655572,
          },
          {
            scmType: 'CODE_GIT',
            aliasName: 'bkdevops/plugins',
            url: 'http://git.woa.com/bkdevops/plugins.git',
            branchName: 'develop',
            newCommitId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0',
            commitTimes: 1,
            mainRepo: false,
            createTime: 1755655603,
          },
        ],
        artifactQuality: {
          BK_CI_SIGNATURE: [
            {
              labelKey: 'BK_CI_SIGNATURE',
              value: 'IN_HOUSE',
              color: '#E1EBFF',
              count: 1,
            },
          ],
          AutoTest: [
            {
              labelKey: 'AutoTest',
              value: 'Pass',
              color: '#2CAF5E',
              count: 3,
            },
          ],
          CodeCoverage: [
            {
              labelKey: 'CodeCoverage',
              value: '85%',
              color: '#2CAF5E',
              count: 1,
            },
          ],
        },
        webhookInfo: {
          codeType: 'GIT',
          nameWithNamespace: 'silverye/stream_server',
          webhookRepoUrl: 'http://git.woa.com/silverye/stream_server.git',
          webhookBranch: 'dev_silver',
          webhookAliasName: 'silverye/stream_server',
          webhookType: 'GIT',
          webhookEventType: 'MERGE_REQUEST',
          webhookMessage: 'add redis clear',
          webhookCommitId: '0534f52fb98459e235cb832703817751ea9783b0',
          refId: '0534f52fb98459e235cb832703817751ea9783b0',
          webhookMergeCommitSha: '',
          webhookSourceBranch: 'feat/add_redis_clear',
          mrId: '22646451',
          mrIid: '192',
          mrUrl: 'http://git.woa.com/silverye/stream_server/merge_requests/192',
          repoAuthUser: 'silverye',
          reviewId: '113357206',
          linkUrl: 'http://git.woa.com/silverye/stream_server/merge_requests/192',
        },
        errorInfoList: [
          {
            errorType: 1,
            errorCode: 'BUILD_FAILED',
            errorMsg: '单元测试执行失败，请检查测试用例',
            taskName: '单元测试',
            stageId: 'stage-2',
            containerId: '1',
            taskId: 'e-test-001',
            matrixFlag: false,
          },
          {
            errorType: 2,
            errorCode: 'TIMEOUT',
            errorMsg: '健康检查超时，服务可能未正常启动',
            taskName: '健康检查',
            stageId: 'stage-5',
            containerId: '5',
            taskId: 'e-health-check-001',
            matrixFlag: false,
          },
        ],
      })
    }, 1000)
  })
}

/**
 * 终止创作流执行
 * @param projectId 项目ID
 * @param flowId 创作流ID
 * @param buildId 构建ID
 * @returns 是否成功终止
 */
export function requestTerminatePipeline({
  projectId,
  flowId,
  buildId,
}: {
  projectId: string
  flowId: string
  buildId: string
}): Promise<boolean> {
  // TODO: 调用实际接口
  // return http.post(`/user/builds/projects/${projectId}/${flowId}/${buildId}`)
  //   .then(res => res.data)

  // Mock 数据
  return new Promise((resolve) => {
    setTimeout(() => {
      // 模拟成功终止
      resolve(true)
    }, 500)
  })
}

/**
 * 重试创作流
 */
export function retryFlow({
  projectId,
  flowId,
  buildId,
}: {
  projectId: string
  flowId: string
  buildId: string
}): Promise<RetryPipelineResponse> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        id: 'b-d8311316d4a04e349f48102f9553b568',
        executeCount: 3,
        projectId: 'default-project',
        pipelineId: 'p-fc1ba8afdea34eed8a95e668879f4115',
        num: 3,
      })
    }, 500)
  })
}

/**
 * 重放创作流
 */
export function replayFlow({
  projectId,
  flowId,
  buildId,
}: {
  projectId: string
  flowId: string
  buildId: string
}): Promise<ReplayPipelineResponse> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        id: 'b-d8311316d4a04e349f48102f9553b568',
        status: 'REPLAYING',
      })
    }, 500)
  })
}

/**
 * 获取启动参数值
 */
export function requestBuildParams({
  projectId,
  pipelineId,
  buildId,
}: {
  projectId: string
  pipelineId: string
  buildId: string
}): Promise<BuildParamItem[]> {
  // TODO: 接入真实接口：return get<BuildParamItem[]>(`/user/builds/${projectId}/${pipelineId}/${buildId}/parameters`, { params })
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          key: 'gdsag',
          value: 'gdsags',
          valueType: 'STRING',
          readOnly: false,
          desc: 'gas',
          defaultValue: 'gdsags',
        },
        {
          key: 'wenjian',
          value: '/TestFile/task.json',
          valueType: 'CUSTOM_FILE',
          readOnly: false,
          desc: '',
          defaultValue: '/TestFile/task.json',
        },
        {
          key: 'jiaoben',
          value:
            '# 通过./xxx.sh的方式执行脚本. 即若脚本中未指定解释器，则使用系统默认的shell  # 旧的${}引用变量的方式已升级为${{}}，和bash原生引用变量的方式区分开  # 通过::set-variable命令字设置/修改全局变量 # echo "::set-variable name=<var_name>::<value>" # 在后续的插件表单中使用表达式${{variables.<var_name>}}引用这个变量 # 注意：旧的通过setEnv设置变量的方式仍然保留，但存在一些历史问题，已停止迭代，不再推荐使用  # 通过::set-output命令字设置当前步骤的输出(变量隔离，不会被覆盖) # echo "::set-output name=<output_name>::<value>" # 在后续的插件表单中使用表达式${{jobs.<job_id>.steps.<step_id>.outputs.<output_name>}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置  # 在质量红线中创建自定义指标后，通过setGateValue函数设置指标值 # setGateValue "CodeCoverage" $myValue # 然后在质量红线选择相应指标和阈值。若不满足，流水线在执行时将会被卡住  # cd $WORKSPACE 可进入当前工作空间目录',
          valueType: 'TEXTAREA',
          readOnly: false,
          desc: '',
          defaultValue:
            '# 通过./xxx.sh的方式执行脚本. 即若脚本中未指定解释器，则使用系统默认的shell  # 旧的${}引用变量的方式已升级为${{}}，和bash原生引用变量的方式区分开  # 通过::set-variable命令字设置/修改全局变量 # echo "::set-variable name=<var_name>::<value>" # 在后续的插件表单中使用表达式${{variables.<var_name>}}引用这个变量 # 注意：旧的通过setEnv设置变量的方式仍然保留，但存在一些历史问题，已停止迭代，不再推荐使用  # 通过::set-output命令字设置当前步骤的输出(变量隔离，不会被覆盖) # echo "::set-output name=<output_name>::<value>" # 在后续的插件表单中使用表达式${{jobs.<job_id>.steps.<step_id>.outputs.<output_name>}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置  # 在质量红线中创建自定义指标后，通过setGateValue函数设置指标值 # setGateValue "CodeCoverage" $myValue # 然后在质量红线选择相应指标和阈值。若不满足，流水线在执行时将会被卡住  # cd $WORKSPACE 可进入当前工作空间目录',
        },
        {
          key: 'FDDSA',
          value: 'FDSA',
          valueType: 'STRING',
          readOnly: false,
          desc: '65465',
          defaultValue: 'FDSA',
        },
        {
          key: 'GDFfds',
          value: 'gdsagdsadsagdsg',
          valueType: 'STRING',
          readOnly: true,
          desc: '',
          defaultValue: 'gdsagdsadsagdsg',
        },
        {
          key: 'gadsgdahhhh',
          value: 'gdsa',
          valueType: 'STRING',
          readOnly: true,
          desc: '',
          defaultValue: 'gdsa',
        },
      ])
    }, 300)
  })
}

/**
 * 获取启动参数组合
 */
export function requestBuildParamCombination({
  projectId,
  pipelineId,
  buildId,
}: {
  projectId: string
  pipelineId: string
  buildId: string
}): Promise<BuildParamProperty[]> {
  // TODO: 接入真实接口
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: 'gdsag',
          name: 'gdsag',
          required: false,
          constant: false,
          type: 'STRING',
          defaultValue: 'gdsags',
          value: 'gdsags',
          desc: 'gas',
          readOnly: false,
          valueNotEmpty: false,
          removeFlag: false,
        },
        {
          id: 'wenjian',
          name: 'wenjian',
          required: false,
          constant: false,
          type: 'CUSTOM_FILE',
          defaultValue: '/TestFile/task.json',
          value: '/TestFile/task.json',
          desc: '',
          readOnly: false,
          valueNotEmpty: false,
          removeFlag: false,
        },
        {
          id: 'jiaoben',
          name: 'jiaoben',
          required: true,
          constant: false,
          type: 'TEXTAREA',
          defaultValue:
            '# 通过./xxx.sh的方式执行脚本. 即若脚本中未指定解释器，则使用系统默认的shell  # 旧的${}引用变量的方式已升级为${{}}，和bash原生引用变量的方式区分开  # 通过::set-variable命令字设置/修改全局变量 # echo "::set-variable name=<var_name>::<value>" # 在后续的插件表单中使用表达式${{variables.<var_name>}}引用这个变量 # 注意：旧的通过setEnv设置变量的方式仍然保留，但存在一些历史问题，已停止迭代，不再推荐使用  # 通过::set-output命令字设置当前步骤的输出(变量隔离，不会被覆盖) # echo "::set-output name=<output_name>::<value>" # 在后续的插件表单中使用表达式${{jobs.<job_id>.steps.<step_id>.outputs.<output_name>}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置  # 在质量红线中创建自定义指标后，通过setGateValue函数设置指标值 # setGateValue "CodeCoverage" $myValue # 然后在质量红线选择相应指标和阈值。若不满足，流水线在执行时将会被卡住  # cd $WORKSPACE 可进入当前工作空间目录',
          value:
            '# 通过./xxx.sh的方式执行脚本. 即若脚本中未指定解释器，则使用系统默认的shell  # 旧的${}引用变量的方式已升级为${{}}，和bash原生引用变量的方式区分开  # 通过::set-variable命令字设置/修改全局变量 # echo "::set-variable name=<var_name>::<value>" # 在后续的插件表单中使用表达式${{variables.<var_name>}}引用这个变量 # 注意：旧的通过setEnv设置变量的方式仍然保留，但存在一些历史问题，已停止迭代，不再推荐使用  # 通过::set-output命令字设置当前步骤的输出(变量隔离，不会被覆盖) # echo "::set-output name=<output_name>::<value>" # 在后续的插件表单中使用表达式${{jobs.<job_id>.steps.<step_id>.outputs.<output_name>}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置  # 在质量红线中创建自定义指标后，通过setGateValue函数设置指标值 # setGateValue "CodeCoverage" $myValue # 然后在质量红线选择相应指标和阈值。若不满足，流水线在执行时将会被卡住  # cd $WORKSPACE 可进入当前工作空间目录',
          desc: '',
          readOnly: false,
          valueNotEmpty: true,
          removeFlag: false,
        },
        {
          id: 'FDDSA',
          name: 'FDSA',
          required: false,
          constant: true,
          type: 'STRING',
          defaultValue: 'FDSA',
          desc: '65465',
          readOnly: false,
          valueNotEmpty: false,
          removeFlag: false,
        },
        {
          id: 'GDFfds',
          name: '运行时只读运行时只读',
          required: true,
          constant: false,
          type: 'STRING',
          defaultValue: 'gdsagdsadsagdsg',
          value: 'gdsagdsadsagdsg',
          desc: '',
          readOnly: true,
          valueNotEmpty: false,
          removeFlag: false,
        },
        {
          id: 'gadsgdahhhh',
          name: '运行时只读',
          required: false,
          constant: false,
          type: 'STRING',
          defaultValue: 'gdsa',
          desc: '',
          readOnly: true,
          valueNotEmpty: false,
          removeFlag: false,
        },
      ])
    }, 300)
  })
}
